name       : caprice32
version    : 4.5.0
release    : 2
source     :
    - https://github.com/ColinPitrat/caprice32/archive/v4.5.0.tar.gz : 5ec8addcc3fb13f71a15c57dead9b458771eb6ad605bd9066f40e592cfb4bb6c
license    : GPL-2.0-or-later
component  : games.emulator
summary    : An emulator of the Amstrad CPC 8bit home computer range.
description: |
    An emulator of the Amstrad CPC 8bit home computer range.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
setup      : |
    sed -i 's,rom_path=.*,rom_path=/usr/share/caprice32/rom/,' cap32.cfg
    sed -i 's,resources_path=.*,resources_path=/usr/share/caprice32/resources/,' cap32.cfg
    sed -i 's,cart_path=.*,cart_path=/usr/share/caprice32/rom/,' cap32.cfg
build      : |
    %make RELEASE=TRUE WITHOUT_GL=TRUE
install    : |
    install -Dm00644 cap32.cfg $installdir/etc/cap32.cfg
    install -Dm00755 cap32 $installdir/usr/bin/cap32
    install -Dm00644 $pkgfiles/caprice32.desktop $installdir/usr/share/applications/caprice32.desktop
    mkdir -p $installdir/usr/share/caprice32/rom
    cp rom/* $installdir/usr/share/caprice32/rom/
    mkdir -p $installdir/usr/share/caprice32/resources
    cp resources/* $installdir/usr/share/caprice32/resources
    chmod -R 00644 $installdir/usr/share/caprice32
