name       : caprice32
version    : 4.6.0
release    : 3
source     :
    - https://github.com/ColinPitrat/caprice32/archive/v4.6.0.tar.gz : bdf89ef5c29a23eaf6858e0afc54d4e0eca1e502b9b0706645305bea31a669e1
license    : GPL-2.0-or-later
component  : games.emulator
summary    : An emulator of the Amstrad CPC 8bit home computer range.
description: |
    An emulator of the Amstrad CPC 8bit home computer range.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
setup      : |
    sed -i 's,rom_path=.*,rom_path=/usr/share/caprice32/rom/,' cap32.cfg
    sed -i 's,resources_path=.*,resources_path=/usr/share/caprice32/resources/,' cap32.cfg
    sed -i 's,cart_path=.*,cart_path=/usr/share/caprice32/rom/,' cap32.cfg
build      : |
    %make RELEASE=TRUE WITHOUT_GL=TRUE
install    : |
    install -Dm00644 cap32.cfg $installdir/etc/cap32.cfg
    install -Dm00755 cap32 $installdir/usr/bin/cap32
    install -Dm00644 resources/freedesktop/caprice32.desktop $installdir/usr/share/applications/caprice32.desktop
    install -Dm00644 resources/freedesktop/caprice32.png $installdir/usr/share/icons/caprice32.png
    install -d $installdir/usr/share/caprice32/rom
    cp rom/* $installdir/usr/share/caprice32/rom/
    install -d $installdir/usr/share/caprice32/resources
    cp -r resources/* $installdir/usr/share/caprice32/resources
    rm -r $installdir/usr/share/caprice32/resources/freedesktop
    chmod -R 00644 $installdir/usr/share/caprice32
