name       : caprice32
version    : 4.3.0
release    : 1
source     :
    - https://github.com/ColinPitrat/caprice32/archive/v4.3.0.tar.gz : 9328f4a75c5dd69ed88f211ff1c9519ab8b868a889fa5d7ff84f80cf7eddd8af
license    : GPL-2.0
component  : games.emulator
summary    : An emulator of the Amstrad CPC 8bit home computer range.
description: |
    An emulator of the Amstrad CPC 8bit home computer range.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(sdl)
setup      : |
    sed -i 's,rom_path=.*,rom_path=/usr/share/caprice32/rom/,' cap32.cfg
    sed -i 's,resources_path=.*,resources_path=/usr/share/caprice32/resources/,' cap32.cfg
    sed -i 's,cart_path=.*,cart_path=/usr/share/caprice32/rom/,' cap32.cfg
build      : |
    %make RELEASE=TRUE WITHOUT_GL=TRUE DEBUG=TRUE
install    : |
    install -D -m00644 cap32.cfg $installdir/etc/cap32.cfg
    install -D -m00755 cap32 $installdir/usr/bin/cap32
    install -D -m00644 $pkgfiles/caprice32.desktop $installdir/usr/share/applications/caprice32.desktop
    mkdir -p $installdir/usr/share/caprice32/rom
    cp rom/* $installdir/usr/share/caprice32/rom/
    mkdir -p $installdir/usr/share/caprice32/resources
    cp resources/* $installdir/usr/share/caprice32/resources
    chmod -R 00644 $installdir/usr/share/caprice32
